spring:
  profiles:
    #使用的开发环境为dev:开发环境 qa:测试环境 prod:生产环境
    active: dev
  datasource:
    #数据库驱动类
    driver-class-name: com.mysql.jdbc.Driver
    #数据库URL地址
    url: jdbc:mysql://23sdk.23h5.cn:3306/db_ydgame?useUnicode=true&characterEncoding=utf8&useSSL=false
    #数据库用户名
    username: root
    #数据库密码
    password: yd123456
    tomcat:
      initialSize: 1
      min-idle: 1
      max-idle: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #生成规则
          auto: update
        #设置对应的方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #设置显示SQL语句
    show-sql: true
    #生成的表名按照自己的命名
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: true
  redis:
      #Redis数据库索引
      database: 0
      #Redis服务器地址
      host: 127.0.0.1
      #Redis服务器连接端口
      port: 6379
      #Redis服务器连接密码，(默认为空)
      password: 
      pool:
        #连接池最大连接数(使用负值标示没有限制)
        max-active: 8
        #连接池最大阻塞等待时间(使用负值标示没有限制)
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中最小空闲连接
        min-idle: 0
      #连接超时时间
      timeout: 0
  #生成163邮箱
  #mail:
      #host: stmp.163.com
      #username: 18237177660@163.com
      #password: csy520csy
      #default-encoding: utf-8
      #properties:
        #mail:
          #smtp:
            #auth: true
            #starttls: 
                #enable: true 
                #required: true
  #生成qq邮箱
  mail:
      host: stmp.qq.com
      username: 12345678@163.com
      password: 123456
      port: 25
      default-encoding: utf-8
      #test-connection: true
      properties:
        mail:
          smtp:
            auth: true
            starttls: 
                enable: true 
                required: true
logging:
  file: logs/logback-${spring.profiles.active}.log
#  config: classpath:log-${spring.profiles.active}.log
