spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_ydgame?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    tomcat:
      initialSize: 1
      min-idle: 1
      max-idle: 20
      max-wait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    cache: true
  mail:
      host: stmp.126.com
      username: yd@126.com
      password: yd123456
      default-encoding: utf-8
logging:
  file: logs/logback-${spring.profiles.active}.log
#  config: classpath:log-${spring.profiles.active}.log
