#开发环境
name: game
server:
  port: 8080
spring:
  mail:
      host: smtp.163.com
      username: znlccy0603@163.com
      password: znlccy06030704
      port: 25
      default-encoding: UTF-8
      protocol: smtp
      properties:
        mail:
          smth:
            auth: true
            starttls:
              enable: true
              required: true
  datasource:
      #数据库驱动类
      driver-class-name: com.mysql.jdbc.Driver
      #数据库URL地址
      url: jdbc:mysql://47.100.106.59:3306/db_ydgame?useUnicode=true&characterEncoding=utf8&useSSL=false
      #数据库用户名
      username: root
      #数据库密码
      password: yd123456
      tomcat:
        initialSize: 1
        min-idle: 1
        max-idle: 20
        max-wait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 30000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
  redis:
    #Redis数据库索引(默认为0)
    database: 0
    host: localhost
    password:
    port: 6379
    pool:
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0
      #连接池中最大连接数(使用负值标示没有限制)
      max-active: -1
      #连接池最大阻塞等待时间(使用负值标示没有限制)
      max-wait: -1
  backhost: 47.100.106.59